version = 0.1

[default.deploy.parameters]
stack_name = "campusflow-backend"
resolve_s3 = true
s3_prefix = "campusflow-backend"
confirm_changeset = true
capabilities = "CAPABILITY_IAM CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND"
parameter_overrides = "Environment=\"dev\""
image_repositories = []

[default.global.parameters]
region = "ap-south-1"
